### ISSUE TITLE
OpenGL and OpenGL Shaders

### ISSUE THREAD

**Issue by KK-MS** [OpenSimulationInterface/osi-visualizer#15]
1. What is the version of OpenGL and OpenGL shaders supported?
2. What is the Graphics card used?

**Comment by CarloVanDriestenBMW** [comment]
The graphic card needs to support the openGL version needed for the functions. According to the documentation [Graphics Drivers](http://doc.qt.io/qt-5/windows-requirements.html)

> For Qt Quick 2 to work, a graphics driver that provides OpenGL 2.1 or higher is required. The default driver from Windows is **OpenGL 1.1**. Qt includes a version of the ANGLE project which is included from the Windows Qt installers. ANGLE implements the OpenGL ES 2.0 API on top of DirectX 11 or DirectX 9. ANGLE requires that the DirectX SDK is installed when building Qt.

**Comment by KK-MS** [comment]
Hello Carlo,

Thank you for the information, it was helpful, 

As suggested in the "General Information", we have environment:
1. Ubuntu Linux 16.04 LTS
2. QT Environment:
```
$ qtcreator -version
Qt Creator 3.5.1 based on Qt 5.5.1
```
with this we observe error:
`"Failed to initialize OpenGL"`

As per our code analysis, OSI viewer is using OpenGL Shaders 430 (as in VertexShader.vert), 
This version of Shaders seems to be not supported in Ubuntu with Intel graphics card. 
We analyzed OpenGL software and Hardware configuration as:
```
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

Do you suggest we should try with Windows OS? Please share the steps.

Thank you for the support,

**Comment by SU-TH** [comment]
Hello Carlo,

I have the same problem.

When I change 
1) the `#include <QOpenGLFunctions_4_3_Core>` from the header and source files to `#include <QOpenGLFunctions_3_0>` and
2) the lines, where `4_3_Core` occurs to `3_0` and
3) `#version 430`  to `#version 320 es` in the files: 'VertexShader.vert' and 'FragmentShader.frag'

the Application Output is:
```
"OpenGL version: 3.0 Mesa 17.2.8"
QOpenGLShader::compile(Fragment): 0:3(1): error: No precision specified in this scope for type `vec2'
0:4(1): error: No precision specified in this scope for type `vec4'
0:7(1): error: No precision specified in this scope for type `vec4'
0:15(24): error: no matching function for call to `textureQueryLod(sampler2D, vec2)'; candidates are:
0:15(24): error: type mismatch
0:15(20): error: cannot construct `int' from a non-numeric data type
0:16(14): error: no matching function for call to `textureLod(sampler2D, vec2, int)'; candidates are:
0:16(14): error:    vec4 textureLod(sampler1D, float, float)
0:16(14): error:    ivec4 textureLod(isampler1D, float, float)
0:16(14): error:    uvec4 textureLod(usampler1D, float, float)
0:16(14): error:    vec4 textureLod(sampler2D, vec2, float)
0:16(14): error:    ivec4 textureLod(isampler2D, vec2, float)
0:16(14): error:    uvec4 textureLod(usampler2D, vec2, float)
0:16(14): error:    vec4 textureLod(sampler3D, vec3, float)
0:16(14): error:    ivec4 textureLod(isampler3D, vec3, float)
0:16(14): error:    uvec4 textureLod(usampler3D, vec3, float)
0:16(14): error:    vec4 textureLod(samplerCube, vec3, float)
0:16(14): error:    ivec4 textureLod(isamplerCube, vec3, float)
0:16(14): error:    uvec4 textureLod(usamplerCube, vec3, float)
0:16(14): error:    float textureLod(sampler1DShadow, vec3, float)
0:16(14): error:    float textureLod(sampler2DShadow, vec3, float)
0:16(14): error:    vec4 textureLod(sampler1DArray, vec2, float)
0:16(14): error:    ivec4 textureLod(isampler1DArray, vec2, float)
0:16(14): error:    uvec4 textureLod(usampler1DArray, vec2, float)
0:16(14): error:    vec4 textureLod(sampler2DArray, vec3, float)
0:16(14): error:    ivec4 textureLod(isampler2DArray, vec3, float)
0:16(14): error:    uvec4 textureLod(usampler2DArray, vec3, float)
0:16(14): error:    vec4 textureLod(samplerCubeArray, vec4, float)
0:16(14): error:    ivec4 textureLod(isamplerCubeArray, vec4, float)
0:16(14): error:    uvec4 textureLod(usamplerCubeArray, vec4, float)
0:16(14): error:    float textureLod(sampler1DArrayShadow, vec3, float)
0:20(6): error: operands of `==' must have the same type

*** Problematic Fragment shader source code ***
#version 320 es
#define lowp
#define mediump
#define highp
#line 2

layout (location = 0) in vec2 texCoord;
layout (location = 0) out vec4 fragColor;
layout (binding = 0) uniform sampler2D objectTexture;

uniform vec4 color;
uniform bool useTexture;

void main(void)
{
	fragColor = color;
	
	if (useTexture) {
		int mipMapLevel = int(textureQueryLod(objectTexture, texCoord).x);
		fragColor = textureLod(objectTexture, texCoord, mipMapLevel);
		//fragColor = texture(objectTexture, texCoord);
	}
	
	if (fragColor.a == 0) {
		discard;
	}
}

***
.../osi-visualizer exited with code 0
```

Thanks for your Support

**Comment by KK-MS** [comment]
Is it possible to provide details about your work environment:
Example:
1. lspci -v
2. glxinfo | Grep OpenGL
3. More details,
This will help us plan the procurement of our new hardware and setup.

**Comment by Yang-Wu-Altran** [comment]
I hope this helps: ( I will try to get more information later)

~$  lspci -v
01:00.0 VGA compatible controller: NVIDIA Corporation GM107GLM [Quadro M2000M] (rev a2) (prog-if 00 [VGA controller])
	Subsystem: Dell GM107GLM [Quadro M2000M]
	Flags: bus master, fast devsel, latency 0, IRQ 136
	Memory at dc000000 (32-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	Memory at c0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at dd000000 [disabled] [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_390, nvidia_390_drm



~$ glxinfo   | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Quadro M2000M/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 390.30
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 390.30
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.30
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by pmai** [comment]
FWIW I would generally recommend using NVidia GPUs with the NVidia proprietary drivers under Linux for OpenGL development at the moment (irrespective of osi-visualizer). Sad state of affairs, but that seems to be the way it is currently.
