### ISSUE TITLE
Data files not able to run

### ISSUE THREAD

**Issue by monishgogri** [OpenSimulationInterface/osi-visualizer#22]
Hello!

I am working with the osi visualizer and have installed in the Ubuntu 18.04 LTS OS.

I tried opening the test files available with me, but always shows the error that not able to read available input files on OSI viewer.

Can you please provide a Data file which runs with OSI viewer.

Thanking you,

Regards.

**Comment by pengtu** [comment]
Can you provide a sample OSI file for people to check that the build works?

Thanks,
Peng.

**Comment by monishgogri** [comment]
I have found these files which do give some graphic output... Although they are not running as expected.
[osidata_1.txt](https://github.com/OpenSimulationInterface/osi-visualizer/files/2079344/osidata_1.txt)
[Uploading osidata_2.txt…]()

**Comment by haoyuanying** [comment]
Hello, the osidata_1 & 2.txt files were built with osi 2.2. Those should be obsoleted and would not work with the osi-visualizer release. A new osi3::SensorView example proto string file is provided together with the release, please download it there and use it to check your build.

**Comment by monishgogri** [comment]
Alright, thank you for the information.

**Comment by monishgogri** [comment]
Hello,
Thank you for the information.
