### ISSUE TITLE
MPL header and copyright disclaimer in source files

### ISSUE THREAD

**Issue by raueATconti** [OpenSimulationInterface/osi-visualizer#24]
- missing MPL header in source files (folders /src and /include) ;
- source files in folder /include do but those in /src do not contain the BMW copyright notice; I guess there's no reason for treating them differently, or? (s.a. note below);

side note: 
according to [https://www.mozilla.org/en-US/MPL/2.0/FAQ/](url) there's no obligation adding copyright ownership;

**Comment by jdsika** [comment]
This will be solved with the cooperation contract with ASAM
