### ISSUE TITLE
Running CMakelist.txt for the first time !

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/osi-visualizer#28]
Hello, I just finished installing OSI and now i am trying to run the visualizer but these errors are being shown in Qt creator. i am new to this and have no idea how to solve them. I am sorry for being lame. but i really need help as it is important for me to run and understand.

![capture](https://user-images.githubusercontent.com/40594242/42563818-71a17144-84ff-11e8-9506-0b45a369549f.JPG)

**Comment by mshaheerm** [comment]
![capture](https://user-images.githubusercontent.com/40594242/42564510-3e88cc1a-8501-11e8-9b7d-022a89224a22.JPG)

**Comment by monishgogri** [comment]
After installing Protobuf, you must also add it as an environment variable.
Try following these instructions:

https://github.com/google/protobuf/releases/tag/v2.6.1

- Download .zip file und unzip files.
- Open protobuf.sln in vsprojects in MS VS (used 2015).
- Build libprotobuf, libprotobuf-lite, libprotoc and protoc.
- Make sure you are using a x64 configuration for building the solutions.
- After compilation run extract_includes.bat to copy the folder
protobuf-2.6.1/src/google into a new directory called “include” , preferably in
C:/Program Files/Protobuf.
- If you get a deprecation error during compilation of libprotobuf you need to
edit the header file "hash.h" in this solution.
Add the following definition before any line of code:
#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS
- Relevant Output:
-- libprotobuf.lib, libprotobuf-lite.lib, libprotoc.lib, protoc.exe, include directory
-- The directory "C:/Program files/protobuf" should look like this:
--- protobuf
    protobuf/bin/protoc.exe
    protobuf/include/google (and google should contain the headers, etc from the build)
    protobuf/lib (lib should contain libprotobuf.lib, libprotobuf-lite.lib, libprotoc.lib)
-Set Environment variables:
-- PATH+= <..>\protobuf\bin
-- PROTOBUF = <..>\protobuf

**Comment by haoyuanying** [comment]
Hello, the current osi-visualizer does not intented to run on Windows. Please use native Ubuntu 16.04 for running it.

**Comment by mshaheerm** [comment]
@monishgogri i have done every step as per you said. now what shall i fill into these?
![capture](https://user-images.githubusercontent.com/40594242/42573729-2fb87430-851d-11e8-94b2-ec018390048a.JPG)

**Comment by mshaheerm** [comment]
@monishgogri @haoyuanying   i cannot configure it. these are the errors and problems
![capture](https://user-images.githubusercontent.com/40594242/42574679-478d1618-851f-11e8-9f54-6c4ddfa08294.JPG)

**Comment by mshaheerm** [comment]
@monishgogri  @haoyuanying  can you please explain what is "desired <path-to-proto2cpp.py>" ?? where shall i copy the proto2cpp repo content in?

**Comment by haoyuanying** [comment]
It is used for osi doxygen, if you do not have it, it does not influnce the osi functionality and building.

**Comment by mshaheerm** [comment]
i do have OSI doxygen. i have compiled it. configured and generated it. but whats the output of generation? i mean what should i have when the configuration and generation is done?  which files are generated as a result and what shall i do next?

**Comment by jdsika** [comment]
@vkresch looks like an installation issue as well. Check quickly if your build instructions (without docker) cover the topics.
