### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by BolinZhou** [OpenSimulationInterface/osi-visualizer#36]
Hi, when i processed to the step "cmake .."
```
It returns:
CMake Warning at open-simulation-interface/CMakeLists.txt:169 (message):
/proto2cpp.py could not be found.


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FMILIB_INCLUDE_DIRS
   used as include directory in directory /home/user/osi-visualizer
   used as include directory in directory /home/user/osi-visualizer
   used as include directory in directory /home/user/osi-visualizer
   used as include directory in directory /home/user/osi-visualizer
   used as include directory in directory /home/user/osi-visualizer
   used as include directory in directory /home/user/osi-visualizer
   used as include directory in directory /home/user/osi-visualizer
FMILIB_LIBRARY
    linked by target "osi-visualizer" in directory /home/user/osi-visualizer

-- Configuring incomplete, errors occurred!
See also "/home/user/osi-visualizer/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/osi-visualizer/build/CMakeFiles/CMakeError.log"

```

Where I changed the path to in the CMakeList.txt to 

`set(FILTER_PROTO2CPP_PY_PATH CACHE PATH "/home/user/osi-visualizer")`

Where could possibly gone wrong? Many thanks

**Comment by pmai** [comment]
@BolinZhou the proto2cpp.py warning can be ignored, since that's only needed for documentation building for the OSI stuff itself.

The real problem is that it is not finding the include and library directories of the FMILibrary, that you need to install as a prerequisite. This either needs to be in places that CMake searches automatically (e.g. the system include and lib directories), or you have to point it manually there, e.g. by editing the CMakeCache.txt settings for FMILIB_INCLUDE_DIRS and FMILIB_LIBRARY to the proper directories.

**Comment by jdsika** [comment]
@vkresch I think this issue will be resolved with the proper readme and instlal instructions for docker. Have a quick look at this, please.

**Comment by vkresch** [comment]
@BolinZhou osi-visualizer depends on the [FMILibrary](https://svn.jmodelica.org/FMILibrary/tags/) (>= 2.0.2) so you need to install it. Here is a small script for the installation which will be added in the [sphinx documentation](https://opensimulationinterface.github.io/osi-documentation/osi-visualizer/README.html) in the future (also as a bash installation script for convenience):
```bash
# Install FMI202
mkdir -p fmi_library
cd fmi_library

FMI_lib_version=2.0.2

fmi_library_include_install_dir=/usr/local/include/fmi-library
fmi_library_lib_install_dir=/usr/local/lib/fmi-library

install_fmi=false

if ! [ -e ${fmi_library_include_install_dir} -a -e ${fmi_library_lib_install_dir} ] ; then
     install_fmi=true
fi

if ${install_fmi}; then
echo "
Downloading FMI library...
"

if [ ! -d $FMI_lib_version ]; then
    wget --no-parent -nH --cut-dirs=2 -r https://svn.jmodelica.org/FMILibrary/tags/$FMI_lib_version/
fi

echo "
Building FMI library...
"
  cd ${FMI_lib_version}
  mkdir -p build
  cd build
  cmake ../. -DCMAKE_BUILD_TYPE=RELEASE
  make -j8 install
  cd ..
  if [[ -d "install" ]]; then
    cd install
      sudo mkdir -p ${fmi_library_include_install_dir}
    if [[ -d ${fmi_library_include_install_dir} ]]; then
      sudo cp -uvrf ./include/* ${fmi_library_include_install_dir}/
    fi
    sudo mkdir -p ${fmi_library_lib_install_dir}
    if [[ -d ${fmi_library_lib_install_dir} ]]; then
      sudo cp -uvrf ./lib/* ${fmi_library_lib_install_dir}/
    fi
  else
      echo "Could not install the fmi-library into usr/local"
  fi
fi

```

**Comment by vkresch** [comment]
@BolinZhou I created a [pull request](https://github.com/OpenSimulationInterface/osi-visualizer/pull/39) with an install script for Ubuntu 18.04 to automate the installation of the dependecies. Try that! Clone osi-visualizer again and run `bash install.sh` in your terminal.
