### ISSUE TITLE
Fix install.sh

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/osi-visualizer#43]
#### Describe the bug
This is taken from #42 
The install.sh script should be rethought completely, given that it does dangerous sudo stuff that has no place in an install script, has misconceptions about shell syntax, does not install but rather runs osi-visualizer in place, and is a bad idea as is.

#### Describe the expected behavior
@pmai please suggest some changes.

**Comment by vkresch** [comment]
@jdsika @pmai thanks for the feedback. I will open a PR and remove the execution part. Please point me to the dangerous sudo stuff or to the correct shell syntax.

**Comment by pmai** [comment]
@vkresch Since I raised this more of less, I've added a PR that splits install.sh into seperate parts, which can individually be run sudo or not run at all if not needed. Please feel free to rif on this PR for more cleanups, whatever.
