### ISSUE TITLE
unable to install the osi-visualizer due to some problems with the FMI library

### ISSUE THREAD

**Issue by Berrazouane-Red** [OpenSimulationInterface/osi-visualizer#46]
I have difficulties when trying to install OSI-Visualizer

more exactly when running the: 
sudo bash build-install-build-deps.sh

.
.
.
#################################
# Installing FMI 2.0.2                                                                  
#################################

Downloading FMI library...

--2020-01-19 14:47:10--  https://svn.jmodelica.org/FMILibrary/tags/2.0.2/
Resolving svn.jmodelica.org (svn.jmodelica.org)... 85.235.1.123
Connecting to svn.jmodelica.org (svn.jmodelica.org)|85.235.1.123|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name ‘svn.jmodelica.org’.
To connect to svn.jmodelica.org insecurely, use `--no-check-certificate'.

Building FMI library...

build-install-build-deps.sh: line 46: cd: 2.0.2: No such file or directory
CMake Error: The source directory "/home/brz/Documents/osi-visualizer/fmi_library" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No rule to make target 'install'.  Stop.
Could not install the fmi-library into usr/local

**Comment by vkresch** [comment]
@Berrazouane-Red thank you for reporting this issue it seems the link to the fmilibrary is down. I will create a PR for an alternative fmi library installation.
