### ISSUE TITLE
Failed to initialize OpenGL functions

### ISSUE THREAD

**Issue by Berrazouane-Red** [OpenSimulationInterface/osi-visualizer#48]
Whenever I launch the osi-visualizer I get: 

"ZMQ version: 4.2.5"
"ZMQ version: 4.2.5"
failed to initialize OpenGL functions
failed to initialize OpenGL functions

but the visualizer appear, however, when I try to run the example_sensor_view.txt
the program closes automatically and I get:

Gtk-Message: 10:14:18.028 :Gtkdialog mapped without a transient parent. this is discouraged.
Segmentation fault (core dumped) 

I checked the OpenGL installation and during that no warning or so appeared

**Comment by vkresch** [comment]
@Berrazouane-Red can you provide some info about your environment? (OS, Hardware specs, Graphic Card, ...)

**Comment by Berrazouane-Red** [comment]
Thank you for your guidance 
I had a problem with the Graphic Card driver 
It is all working now ^^

**Comment by vkresch** [comment]
@Berrazouane-Red nice to hear so I'm closing this issue.

**Comment by inatale93** [comment]
I am having the same issue on Ubuntu with a GP104GL [Quadro P4000] graphic card. WHat was the solution to this issue?

**Comment by vkresch** [comment]
@inatale93 try to update/install nvidia drivers for your graphics card in ubuntu
