### ISSUE TITLE
osi file format

### ISSUE THREAD

**Issue by racheali** [OpenSimulationInterface/osi-visualizer#9]
when using the visualizer in playback mode -what is the expected format of the osi file?
thanks

**Comment by Yang-Wu-Altran** [comment]
The file format is OpenSimulationInterface (internally serialized google-protobuf).

**Comment by haoyuanying** [comment]
hello, please check the new release, a reference osi3::SensorView proto string file is provided. Once you want to playback your own file, please serialize the osi3 (either SensorData or SensorView) data to string. The splitter between osi3 proto strings is pre-defined as "$$__$$".

**Comment by vkresch** [comment]
Just for an update. See the documentation for the new OSI format [here](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/fileformat.html). Also see this [PR](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/358).
